In [1]:
import subprocess
import os
import torch
import sys, pathlib
from transformers import AutoModelForCausalLM, AutoTokenizer
from llm_blender.pair_ranker.pairrm import DebertaV2PairRM

from torch.utils.data import DataLoader
from datasets import load_dataset, concatenate_datasets, DatasetDict
import torch.nn.functional as F
from tqdm import tqdm
import re
import yaml

LOCAL_TRL_PARENT = "/root/autodl-tmp/Self_play_DRPO"
if LOCAL_TRL_PARENT not in sys.path:
    sys.path.insert(0, LOCAL_TRL_PARENT)

    
# now the import will use your local copy:
from trl import (
    DPOTrainer,
    DPOConfig,
    ModelConfig,
    DRPOTrainer,
    DRPOConfig,
)

from trl.trainer.drpo_utils import GPMwithRewardNetwork, estDPOStylePipeline, BTRewardNetwork, PariRMPipeline

# Load environment variables from /etc/network_turbo
result = subprocess.run('bash -c "source /etc/network_turbo && env | grep proxy"', shell=True, capture_output=True, text=True)
output = result.stdout
for line in output.splitlines():
    if '=' in line:
        var, value = line.split('=', 1)
        os.environ[var] = value

def strip_prompt(prompt: str, text: str) -> str:
    """
    If `text` literally starts with `prompt` (ignoring leading/trailing
    whitespace), cut that prefix off and return the remainder.
    """
    p = prompt.strip()
    # Escaping safeguards punctuation / regex metacharacters
    pattern = r"^\s*" + re.escape(p) + r"\s*"
    return re.sub(pattern, "", text, count=1).lstrip()

/root/autodl-tmp/Self_play_DRPO/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ImportError: cannot import name 'PariRMPipeline' from 'trl.trainer.drpo_utils' (/root/autodl-tmp/Self_play_DRPO/trl/trainer/drpo_utils.py)

In [61]:
"""
ds_ultrafeed_train = load_dataset("openbmb/UltraFeedback", split = 'train', cache_dir="/root/autodl-tmp/dataset")
ds_ultrafeed_train = ds_ultrafeed_train.filter(lambda x: len(x['completions']) > 0)
def get_preferred(sample):
    prompt = sample['instruction']
    sample_completions = sample['completions']
    scores = [sample_completions[i]['overall_score'] for i in range(len(sample_completions))]
    responses = [sample_completions[i]['response'] for i in range(len(sample_completions))]
    preferred_index = scores.index(max(scores))
    dispreferred_index = scores.index(min(scores))
    preferred_ans = responses[preferred_index]
    dispreferred_ans = responses[dispreferred_index]
    return {
        'prompt':prompt,
        'preferred': preferred_ans,
        'dispreferred': dispreferred_ans,
    }
    
processed_dataset = ds_ultrafeed_train.map(get_preferred, remove_columns=ds_ultrafeed_train.column_names)
processed_dataset.push_to_hub("august66/DRPO_data_from_ultrafeed", split="train")
"""

'\nds_ultrafeed_train = load_dataset("openbmb/UltraFeedback", split = \'train\', cache_dir="/root/autodl-tmp/dataset")\nds_ultrafeed_train = ds_ultrafeed_train.filter(lambda x: len(x[\'completions\']) > 0)\ndef get_preferred(sample):\n    prompt = sample[\'instruction\']\n    sample_completions = sample[\'completions\']\n    scores = [sample_completions[i][\'overall_score\'] for i in range(len(sample_completions))]\n    responses = [sample_completions[i][\'response\'] for i in range(len(sample_completions))]\n    preferred_index = scores.index(max(scores))\n    dispreferred_index = scores.index(min(scores))\n    preferred_ans = responses[preferred_index]\n    dispreferred_ans = responses[dispreferred_index]\n    return {\n        \'prompt\':prompt,\n        \'preferred\': preferred_ans,\n        \'dispreferred\': dispreferred_ans,\n    }\n\nprocessed_dataset = ds_ultrafeed_train.map(get_preferred, remove_columns=ds_ultrafeed_train.column_names)\nprocessed_dataset.push_to_hub("august66/

In [ ]:
seed = 42
FIRST = 100
SECOND = 20_000
data_cache_path = "/root/autodl-tmp/dataset"
drpo_train = load_dataset("august66/DRPO_data_from_ultrafeed", split="train", cache_dir=data_cache_path)
drpo_train = drpo_train.rename_columns({
    "preferred": "a1",
    "dispreferred":"a2",
})
ones = [1] * drpo_train.num_rows 
drpo_train = drpo_train.add_column("rank", ones)


def process_split(original):
    swapped = original.map(lambda x: {
        'a1': x['a2'],
        'a2': x['a1'],
        # 'rank': 1 - int(random.random() < x['chosen_preference']),
        'rank': 1 - x['rank'],
    })

    return concatenate_datasets([original, swapped]).shuffle(seed=seed)
drpo_train = process_split(drpo_train)
drpo_train_reshuffle = drpo_train.shuffle(seed=seed)
drpo_train_split_1 = drpo_train_reshuffle.select(range(FIRST))
drpo_train_split_2 = drpo_train_reshuffle.select(range(FIRST, FIRST + SECOND))
drpo_train_split_3 = drpo_train_reshuffle.select(range(FIRST + SECOND, len(drpo_train_reshuffle)))

In [2]:
device = 'cuda'
model_name = "Kyleyee/Qwen2.5-1.5B-sft-hh-3e"   # use 0.5B model to test for now 
cache_path = "/root/autodl-tmp/model_cache"
model_args = ModelConfig(model_name)
model_torch_dtype = torch.float16
model_args.trust_remote_code = True
model_kwargs = dict(
    revision = model_args.model_revision,
    torch_dtype = model_torch_dtype, 
    trust_remote_code = model_args.trust_remote_code,
)
lm_model_instance = AutoModelForCausalLM.from_pretrained(
    model_args.model_name_or_path,
    **model_kwargs,
    cache_dir = cache_path,
)

ref_model = AutoModelForCausalLM.from_pretrained(
    model_args.model_name_or_path,
    **model_kwargs,
    cache_dir = cache_path,
)

lm_model_tokenizer = AutoTokenizer.from_pretrained(
    model_args.model_name_or_path, 
    padding_side = 'left', 
    use_fast = True,
    trust_remote_code = model_args.trust_remote_code,
    cache_dir = cache_path
)

if not lm_model_tokenizer.pad_token:
    lm_model_tokenizer.pad_token = lm_model_tokenizer.eos_token

ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/Kyleyee/Qwen2.5-1.5B-sft-hh-3e/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f22c88d4a10>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 9205f69d-f9f5-400d-9474-44819a40f9da)')

In [4]:


with open("/root/autodl-tmp/Self_play_DRPO/DRPO_scripts/hh/train_configs/config_gpm.yaml", "r") as f:
    training_args_config = yaml.safe_load(f)


training_args = DRPOConfig(
    **training_args_config
)
"""
training_args.preference_model_id = 'llm-blender/PairRM-hf'

preference_pipeline = PariRMPipeline(
    model_name_or_path = training_args.preference_model_id,
)
"""

if training_args.is_bt_model:
    if isinstance(training_args.preference_model_id, dict):
        preference_pipeline = estDPOStylePipeline(training_args.preference_model_id)
    else: 
        preference_pipeline = BTRewardNetwork(training_args.preference_model_id, revision=training_args.preference_model_revision)
else:
    preference_pipeline = GPMwithRewardNetwork(training_args.preference_model_id)

trainer = DRPOTrainer(
    model=lm_model_instance,
    ref_model=ref_model,
    preference_model=preference_pipeline ,
    train_dataset = drpo_train_split_1,
    processing_class=lm_model_tokenizer,
    args=training_args,
)

trainer.train()


Fetching 8 files: 100%|██████████| 8/8 [00:00<00:00, 86258.18it/s]


GPTNeoXConfig {
  "architectures": [
    "CustomRewardModel"
  ],
  "attention_bias": true,
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "classifier_dropout": 0.1,
  "eos_token_id": 0,
  "hidden_act": "gelu",
  "hidden_dropout": 0.0,
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neox",
  "num_attention_heads": 8,
  "num_hidden_layers": 16,
  "partial_rotary_factor": 0.25,
  "rope_scaling": null,
  "rope_theta": 10000,
  "rotary_emb_base": 10000,
  "rotary_pct": 0.25,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.52.4",
  "use_cache": true,
  "use_parallel_residual": true,
  "vocab_size": 50304
}

after chat template dataset sample: {'prompt': 'You will be given a definition of a task first, then some input of the task.\nIn this task, you are given a hateful post in Bengali that expresses hate or encourages violence towar

OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 4.69 MiB is free. Process 272376 has 23.67 GiB memory in use. Of the allocated memory 22.63 GiB is allocated by PyTorch, and 759.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [32]:
trainer

In [16]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import llm_blender
blender = llm_blender.Blender()
# Load Ranker
blender.loadranker("llm-blender/PairRM") # load ranker checkpoint
inputs = ["hello!"]
candidates_A = ["hi!"]
candidates_B = ["f**k off!"]
logits = blender.compare(inputs, candidates_A, candidates_B, return_logits=True, mode="[A,B]")
comparison_results = logits > 0
print(logits)
# [ 1.9   -1.255]
print(comparison_results)
# tensor([ True, False], device='cuda:0'), which means whether candidate A is better than candidate B for each input


Successfully loaded ranker from  /root/.cache/huggingface/hub/llm-blender/PairRM


Ranking candidates: 100%|██████████| 1/1 [00:00<00:00, 29.44it/s]

[1.898]
[ True]


In [2]:
pairrm = PariRMPipeline(
    model_name_or_path = 'llm-blender/PairRM-hf',
)

In [3]:
inputs = ["hello!", "I love you!"]
candidates_A = ["hi!", "I hate you!"]
candidates_B = ["f**k off!", "I love you, too!"]

In [4]:
torch.tensor(pairrm(inputs, candidates_A, candidates_B)).sigmoid()

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


tensor([0.8699, 0.2219])

In [8]:
type(pairrm.model)

llm_blender.pair_ranker.pairrm.DebertaV2PairRM

In [6]:
isinstance(pairrm.model, DebertaV2PairRM)

True

In [6]:
from trl.trainer.drpo_utils import get_preference_score
get_preference_score(pairrm, candidates_A, candidates_B, inputs = inputs, kwargs = {})

tensor([0.8699, 0.2219])

In [ ]:
drpo_train_split_1_test = drpo_train_split_1.select(range(100))

In [30]:
training_args['report']

TypeError: 'DRPOConfig' object is not subscriptable

In [19]:
drpo_train

Dataset({
    features: ['prompt', 'preferred', 'dispreferred'],
    num_rows: 63966
})

In [6]:
gpm_model = 'Kyleyee/gpm_tldr_3e'
gpm = AutoModelForCausalLM.from_pretrained(
    gpm_model,
    cache_dir = cache_path,
)

In [8]:
type(gpm)

transformers.models.gpt_neox.modeling_gpt_neox.GPTNeoXForCausalLM

In [10]:
gpm(torch.tensor(['a']))

ValueError: too many dimensions 'str'